exclude: (^notebooks/)
repos:
  # export python requirements https://pdm.fming.dev/latest/usage/advanced/
  - repo: https://github.com/pdm-project/pdm
    rev: 2.9.3 # a PDM release exposing the hook
    hooks:
      - id: pdm-export
        # command arguments, e.g.:
        args: ["-o", "requirements.txt", "--without-hashes"]
        files: ^pdm.lock$
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: codespell
        language: system
        types: [file, python]
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        require_serial: true
        args: ["-c", "bandit.yml"]
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [file, python]
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [file, python]
