site_name: "Watz Python SDK"
site_url: "https://watz-inc.github.io/watz-py/" # Trailing slash is recommended
repo_url: "https://github.com/watz-inc/watz-py"

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight

  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    scheme: slate # This is just dark mode:
    primary: custom
    accent: custom

plugins:
  - mike
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: watz-inc/watz-py
      branch: main
  - search

  # https://mkdocstrings.github.io/recipes/?h=recip#automatic-code-reference-pages
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
            inherited_members: true

markdown_extensions:
  - pymdownx.snippets

extra:
  version:
    provider: mike

nav:
  - Home:
      - index.md
  # defer to gen-files + literate-nav https://mkdocstrings.github.io/recipes/?h=recip#automatic-code-reference-pages
  - Code Reference: reference/ # Note the trailing slash is important
  - Contributing:
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
  - LICENSE.md
