site_name: "Watz Python SDK"
site_url: "https://watz-inc.github.io/watz-py/" # Trailing slash is recommended
repo_url: "https://github.com/watz-inc/watz-py"

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight

  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    scheme: slate # This is just dark mode:
    primary: custom
    accent: custom

plugins:
  - mike
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: watz-inc/watz-py
      branch: main
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.snippets

extra:
  version:
    provider: mike

nav:
  - Home:
      - index.md
  - API:
      - reference.md
  - Contributing:
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
  - LICENSE.md
